services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=quran'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=user'
    ports:
      - '27017'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
